p# Site settings
title: "Necip BARAN"
description: "Resume about Necip BARAN"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Necip BARAN"
resume_title:                   "Senior Software Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "necipbaran42@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "00905536278253"
resume_contact_address:         "Karanfil Sokak Kızılay /Ankara"

resume_header_contact_info:     "Karanfil Sokak Kızılay /Ankara • 00905536278253 • necipbaran42@gmail.comm"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hello, I am Necip BARAN. I have been involved in software development processes since 2008. Software is more than a job for me, it is a way of life and an invaluable passion.When I do my job, I try to create a perfect work of art rather than writing code.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
